### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by v4ltages** [dustinrouillard/lanyard-online-users#3]
After waiting for a bit, it error's out like this this.
Something seems to be undefined.

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at G (90-bd81ea15ff6b878d.js:1:8918)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Ku (framework-5f4595e5518b5600.js:1:111712)
    at Li (framework-5f4595e5518b5600.js:1:98953)
    at Ni (framework-5f4595e5518b5600.js:1:98881)
    at Pi (framework-5f4595e5518b5600.js:1:98744)
    at bi (framework-5f4595e5518b5600.js:1:95710)
    at framework-5f4595e5518b5600.js:1:45204
    at t.unstable_runWithPriority (framework-5f4595e5518b5600.js:1:129336)
    at Ql (framework-5f4595e5518b5600.js:1:44981)
cu @ framework-5f4595e5518b5600.js:1

main-01df828e572375b9.js:1 TypeError: Cannot read properties of undefined (reading 'startsWith')
    at G (90-bd81ea15ff6b878d.js:1:8918)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Ku (framework-5f4595e5518b5600.js:1:111712)
    at Li (framework-5f4595e5518b5600.js:1:98953)
    at Ni (framework-5f4595e5518b5600.js:1:98881)
    at Pi (framework-5f4595e5518b5600.js:1:98744)
    at bi (framework-5f4595e5518b5600.js:1:95710)
    at framework-5f4595e5518b5600.js:1:45204
    at t.unstable_runWithPriority (framework-5f4595e5518b5600.js:1:129336)
    at Ql (framework-5f4595e5518b5600.js:1:44981)
ye @ main-01df828e572375b9.js:1

main-01df828e572375b9.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by v4ltages** [comment]
Seems to be functioning now. :+1:
